//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Company.WebService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        private int Department_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int Department_Id {
            get {
                return this.Department_IdField;
            }
            set {
                if ((this.Department_IdField.Equals(value) != true)) {
                    this.Department_IdField = value;
                    this.RaisePropertyChanged("Department_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WebService.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем GetEmployersResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployers", ReplyAction="*")]
        Company.WebService.GetEmployersResponse GetEmployers(Company.WebService.GetEmployersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetEmployers", ReplyAction="*")]
        System.Threading.Tasks.Task<Company.WebService.GetEmployersResponse> GetEmployersAsync(Company.WebService.GetEmployersRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем GetDepartmentsResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartments", ReplyAction="*")]
        Company.WebService.GetDepartmentsResponse GetDepartments(Company.WebService.GetDepartmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDepartments", ReplyAction="*")]
        System.Threading.Tasks.Task<Company.WebService.GetDepartmentsResponse> GetDepartmentsAsync(Company.WebService.GetDepartmentsRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем name из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployer", ReplyAction="*")]
        Company.WebService.UpdateEmployerResponse UpdateEmployer(Company.WebService.UpdateEmployerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployer", ReplyAction="*")]
        System.Threading.Tasks.Task<Company.WebService.UpdateEmployerResponse> UpdateEmployerAsync(Company.WebService.UpdateEmployerRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем name из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEmployer", ReplyAction="*")]
        Company.WebService.InsertEmployerResponse InsertEmployer(Company.WebService.InsertEmployerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertEmployer", ReplyAction="*")]
        System.Threading.Tasks.Task<Company.WebService.InsertEmployerResponse> InsertEmployerAsync(Company.WebService.InsertEmployerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployer", ReplyAction="*")]
        void DeleteEmployer(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployer", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteEmployerAsync(int id);
        
        // CODEGEN: Контракт генерации сообщений с именем depName из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDepartment", ReplyAction="*")]
        Company.WebService.InsertDepartmentResponse InsertDepartment(Company.WebService.InsertDepartmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/InsertDepartment", ReplyAction="*")]
        System.Threading.Tasks.Task<Company.WebService.InsertDepartmentResponse> InsertDepartmentAsync(Company.WebService.InsertDepartmentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployers", Namespace="http://tempuri.org/", Order=0)]
        public Company.WebService.GetEmployersRequestBody Body;
        
        public GetEmployersRequest() {
        }
        
        public GetEmployersRequest(Company.WebService.GetEmployersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetEmployersRequestBody {
        
        public GetEmployersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetEmployersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetEmployersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Company.WebService.GetEmployersResponseBody Body;
        
        public GetEmployersResponse() {
        }
        
        public GetEmployersResponse(Company.WebService.GetEmployersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetEmployersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Company.WebService.Employer[] GetEmployersResult;
        
        public GetEmployersResponseBody() {
        }
        
        public GetEmployersResponseBody(Company.WebService.Employer[] GetEmployersResult) {
            this.GetEmployersResult = GetEmployersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartments", Namespace="http://tempuri.org/", Order=0)]
        public Company.WebService.GetDepartmentsRequestBody Body;
        
        public GetDepartmentsRequest() {
        }
        
        public GetDepartmentsRequest(Company.WebService.GetDepartmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDepartmentsRequestBody {
        
        public GetDepartmentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDepartmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDepartmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Company.WebService.GetDepartmentsResponseBody Body;
        
        public GetDepartmentsResponse() {
        }
        
        public GetDepartmentsResponse(Company.WebService.GetDepartmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDepartmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Company.WebService.Department[] GetDepartmentsResult;
        
        public GetDepartmentsResponseBody() {
        }
        
        public GetDepartmentsResponseBody(Company.WebService.Department[] GetDepartmentsResult) {
            this.GetDepartmentsResult = GetDepartmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployer", Namespace="http://tempuri.org/", Order=0)]
        public Company.WebService.UpdateEmployerRequestBody Body;
        
        public UpdateEmployerRequest() {
        }
        
        public UpdateEmployerRequest(Company.WebService.UpdateEmployerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int department_id;
        
        public UpdateEmployerRequestBody() {
        }
        
        public UpdateEmployerRequestBody(int id, string name, string lastName, int department_id) {
            this.id = id;
            this.name = name;
            this.lastName = lastName;
            this.department_id = department_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Company.WebService.UpdateEmployerResponseBody Body;
        
        public UpdateEmployerResponse() {
        }
        
        public UpdateEmployerResponse(Company.WebService.UpdateEmployerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateEmployerResponseBody {
        
        public UpdateEmployerResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEmployerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEmployer", Namespace="http://tempuri.org/", Order=0)]
        public Company.WebService.InsertEmployerRequestBody Body;
        
        public InsertEmployerRequest() {
        }
        
        public InsertEmployerRequest(Company.WebService.InsertEmployerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertEmployerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int department_id;
        
        public InsertEmployerRequestBody() {
        }
        
        public InsertEmployerRequestBody(string name, string lastName, int department_id) {
            this.name = name;
            this.lastName = lastName;
            this.department_id = department_id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertEmployerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertEmployerResponse", Namespace="http://tempuri.org/", Order=0)]
        public Company.WebService.InsertEmployerResponseBody Body;
        
        public InsertEmployerResponse() {
        }
        
        public InsertEmployerResponse(Company.WebService.InsertEmployerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertEmployerResponseBody {
        
        public InsertEmployerResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDepartmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDepartment", Namespace="http://tempuri.org/", Order=0)]
        public Company.WebService.InsertDepartmentRequestBody Body;
        
        public InsertDepartmentRequest() {
        }
        
        public InsertDepartmentRequest(Company.WebService.InsertDepartmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class InsertDepartmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string depName;
        
        public InsertDepartmentRequestBody() {
        }
        
        public InsertDepartmentRequestBody(string depName) {
            this.depName = depName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class InsertDepartmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="InsertDepartmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public Company.WebService.InsertDepartmentResponseBody Body;
        
        public InsertDepartmentResponse() {
        }
        
        public InsertDepartmentResponse(Company.WebService.InsertDepartmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class InsertDepartmentResponseBody {
        
        public InsertDepartmentResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : Company.WebService.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<Company.WebService.WebServiceSoap>, Company.WebService.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Company.WebService.GetEmployersResponse Company.WebService.WebServiceSoap.GetEmployers(Company.WebService.GetEmployersRequest request) {
            return base.Channel.GetEmployers(request);
        }
        
        public Company.WebService.Employer[] GetEmployers() {
            Company.WebService.GetEmployersRequest inValue = new Company.WebService.GetEmployersRequest();
            inValue.Body = new Company.WebService.GetEmployersRequestBody();
            Company.WebService.GetEmployersResponse retVal = ((Company.WebService.WebServiceSoap)(this)).GetEmployers(inValue);
            return retVal.Body.GetEmployersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Company.WebService.GetEmployersResponse> Company.WebService.WebServiceSoap.GetEmployersAsync(Company.WebService.GetEmployersRequest request) {
            return base.Channel.GetEmployersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Company.WebService.GetEmployersResponse> GetEmployersAsync() {
            Company.WebService.GetEmployersRequest inValue = new Company.WebService.GetEmployersRequest();
            inValue.Body = new Company.WebService.GetEmployersRequestBody();
            return ((Company.WebService.WebServiceSoap)(this)).GetEmployersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Company.WebService.GetDepartmentsResponse Company.WebService.WebServiceSoap.GetDepartments(Company.WebService.GetDepartmentsRequest request) {
            return base.Channel.GetDepartments(request);
        }
        
        public Company.WebService.Department[] GetDepartments() {
            Company.WebService.GetDepartmentsRequest inValue = new Company.WebService.GetDepartmentsRequest();
            inValue.Body = new Company.WebService.GetDepartmentsRequestBody();
            Company.WebService.GetDepartmentsResponse retVal = ((Company.WebService.WebServiceSoap)(this)).GetDepartments(inValue);
            return retVal.Body.GetDepartmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Company.WebService.GetDepartmentsResponse> Company.WebService.WebServiceSoap.GetDepartmentsAsync(Company.WebService.GetDepartmentsRequest request) {
            return base.Channel.GetDepartmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Company.WebService.GetDepartmentsResponse> GetDepartmentsAsync() {
            Company.WebService.GetDepartmentsRequest inValue = new Company.WebService.GetDepartmentsRequest();
            inValue.Body = new Company.WebService.GetDepartmentsRequestBody();
            return ((Company.WebService.WebServiceSoap)(this)).GetDepartmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Company.WebService.UpdateEmployerResponse Company.WebService.WebServiceSoap.UpdateEmployer(Company.WebService.UpdateEmployerRequest request) {
            return base.Channel.UpdateEmployer(request);
        }
        
        public void UpdateEmployer(int id, string name, string lastName, int department_id) {
            Company.WebService.UpdateEmployerRequest inValue = new Company.WebService.UpdateEmployerRequest();
            inValue.Body = new Company.WebService.UpdateEmployerRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.lastName = lastName;
            inValue.Body.department_id = department_id;
            Company.WebService.UpdateEmployerResponse retVal = ((Company.WebService.WebServiceSoap)(this)).UpdateEmployer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Company.WebService.UpdateEmployerResponse> Company.WebService.WebServiceSoap.UpdateEmployerAsync(Company.WebService.UpdateEmployerRequest request) {
            return base.Channel.UpdateEmployerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Company.WebService.UpdateEmployerResponse> UpdateEmployerAsync(int id, string name, string lastName, int department_id) {
            Company.WebService.UpdateEmployerRequest inValue = new Company.WebService.UpdateEmployerRequest();
            inValue.Body = new Company.WebService.UpdateEmployerRequestBody();
            inValue.Body.id = id;
            inValue.Body.name = name;
            inValue.Body.lastName = lastName;
            inValue.Body.department_id = department_id;
            return ((Company.WebService.WebServiceSoap)(this)).UpdateEmployerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Company.WebService.InsertEmployerResponse Company.WebService.WebServiceSoap.InsertEmployer(Company.WebService.InsertEmployerRequest request) {
            return base.Channel.InsertEmployer(request);
        }
        
        public void InsertEmployer(string name, string lastName, int department_id) {
            Company.WebService.InsertEmployerRequest inValue = new Company.WebService.InsertEmployerRequest();
            inValue.Body = new Company.WebService.InsertEmployerRequestBody();
            inValue.Body.name = name;
            inValue.Body.lastName = lastName;
            inValue.Body.department_id = department_id;
            Company.WebService.InsertEmployerResponse retVal = ((Company.WebService.WebServiceSoap)(this)).InsertEmployer(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Company.WebService.InsertEmployerResponse> Company.WebService.WebServiceSoap.InsertEmployerAsync(Company.WebService.InsertEmployerRequest request) {
            return base.Channel.InsertEmployerAsync(request);
        }
        
        public System.Threading.Tasks.Task<Company.WebService.InsertEmployerResponse> InsertEmployerAsync(string name, string lastName, int department_id) {
            Company.WebService.InsertEmployerRequest inValue = new Company.WebService.InsertEmployerRequest();
            inValue.Body = new Company.WebService.InsertEmployerRequestBody();
            inValue.Body.name = name;
            inValue.Body.lastName = lastName;
            inValue.Body.department_id = department_id;
            return ((Company.WebService.WebServiceSoap)(this)).InsertEmployerAsync(inValue);
        }
        
        public void DeleteEmployer(int id) {
            base.Channel.DeleteEmployer(id);
        }
        
        public System.Threading.Tasks.Task DeleteEmployerAsync(int id) {
            return base.Channel.DeleteEmployerAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Company.WebService.InsertDepartmentResponse Company.WebService.WebServiceSoap.InsertDepartment(Company.WebService.InsertDepartmentRequest request) {
            return base.Channel.InsertDepartment(request);
        }
        
        public void InsertDepartment(string depName) {
            Company.WebService.InsertDepartmentRequest inValue = new Company.WebService.InsertDepartmentRequest();
            inValue.Body = new Company.WebService.InsertDepartmentRequestBody();
            inValue.Body.depName = depName;
            Company.WebService.InsertDepartmentResponse retVal = ((Company.WebService.WebServiceSoap)(this)).InsertDepartment(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Company.WebService.InsertDepartmentResponse> Company.WebService.WebServiceSoap.InsertDepartmentAsync(Company.WebService.InsertDepartmentRequest request) {
            return base.Channel.InsertDepartmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<Company.WebService.InsertDepartmentResponse> InsertDepartmentAsync(string depName) {
            Company.WebService.InsertDepartmentRequest inValue = new Company.WebService.InsertDepartmentRequest();
            inValue.Body = new Company.WebService.InsertDepartmentRequestBody();
            inValue.Body.depName = depName;
            return ((Company.WebService.WebServiceSoap)(this)).InsertDepartmentAsync(inValue);
        }
    }
}
